### ISSUE TITLE
dnsaddr code?

### ISSUE THREAD

**Issue by richardschneider** [multiformats/go-multiaddr-dns#7]
The code for `dnsaddr` is not **consistent**.
- go uses code [12345](https://github.com/multiformats/go-multiaddr-dns/blob/08b97f4c17de51a7ce22ba3b4c814bef84cb2d45/dns.go#L25)
- js uses code [53](https://github.com/multiformats/js-multiaddr/blob/99a1aa4d27e333e2ce0f83dc5160112dc733d0e5/src/protocols-table.js#L33)
- [protocols.csv](https://github.com/multiformats/multiaddr/blob/master/protocols.csv) does not mention `dnsaddr` but has a `dns` at code 53.

Can someone please clarify! cc: @diasdavid @whyrusleeping

**Comment by whyrusleeping** [comment]
Youre gonna have to ask @lgierth on that one. I don't know

**Comment by diasdavid** [comment]
AFAIU, @lgierth renamed `dns` to `dnsaddr`, which was 53 from early days -- https://github.com/multiformats/multiaddr/blob/master/protocols.csv#L7 --. @lgierth Any reason why you didn't update the multiaddr spec and protocol table https://github.com/multiformats/multiaddr ?

`12345` looks like a "typed out random number" :)

**Comment by richardschneider** [comment]
@lgierth any comment?

**Comment by lgierth** [comment]
Sorry - this was a really silly oversight from early development on this :/ Let's go with js's 53.

**Comment by richardschneider** [comment]
Why `dnsaddr` and not just `dns`?

**Comment by lgierth** [comment]
Actually, let's keep 53 reserved for any future /dns protocol. I've filed multiformats/multiaddr#61, multiformats/go-multiaddr-dns#8, and multiformats/js-multiaddr#59, and @ianopolous did multiformats/java-multiaddr#3a6d6548.

@richardschneider if that's cool with you do you wanna update net-ipfs-core too? (you referenced a commit up there)

> Why dnsaddr and not just dns?

dnsaddr is the multiaddr-equivalent of dnslink -- we put multiaddrs into a DNS record, and `/dnsaddr` lets us resolve through them. This is used e.g. in go-ipfs's default bootstrap config. `/dns` on the other hand should be reserved for a "broader" dns address protocol, should there ever be the need for one in the future.

**Comment by lgierth** [comment]
I think this inconsistency is resolved once:
- [ ] multiformats/multiaddr#61
- [ ] multiformats/go-multiaddr-dns#8
- [ ] multiformats/js-multiaddr#59
- [x] java-multiaddr
- [ ] net-ipfs-core

**Comment by richardschneider** [comment]
@lgierth change the code in `net-ipfs-core`, you can now tick it!

**Comment by richardschneider** [comment]
> we put multiaddrs into a DNS record, and /dnsaddr lets us resolve through them. 

I think I'm resolving `dnsaddr` incorrectly, see [peer talk](https://github.com/richardschneider/net-ipfs-engine/blob/0703569172418c1dbe2ddabb7cf5dd3e49392283/PeerTalk/src/MultiAddressExtensions.cs#L89).  Basically I'm accepting any A or AAAA resource record from DNS.

Could you detail or point me to a spec on how to resolve `dnsaddr`?  Is this some magick/hackery with TXT records?

**Comment by lgierth** [comment]
Thanks @diasdavid -- all the impls can slowly roll this out with their next releases then.

@richardschneider There's unfortunately no proper spec, only the examples in the readme of this repo.
